### ISSUE TITLE
Windows line endings not supported ?

### ISSUE THREAD

**Issue by JTriggerFish** [DongHoonPark/ltspice_pytool#13]
Hello,

I was trying to load a simple circuit and got the error below on windows 10, it looks like a line ending issue ?

 attached

C:\PycharmProjects\circuitSim_tests\venv\Scripts\python.exe C:/PycharmProjects/circuitSim_tests/main.py
Traceback (most recent call last):
  File "C:\PycharmProjects\circuitSim_tests\venv\lib\site-packages\ltspice\ltspice.py", line 68, in read_header
    line = str(bytes(data[fp_line_begin:fp_line_end+2]), encoding='UTF16')
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x53 in position 10: truncated data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/PycharmProjects/circuitSim_tests/main.py", line 22, in <module>
    main()
  File "C://PycharmProjects/circuitSim_tests/main.py", line 10, in main
    l = ltspice.Ltspice(file_name)
  File "C:\\PycharmProjects\circuitSim_tests\venv\lib\site-packages\ltspice\ltspice.py", line 45, in __init__
    self.read_header()
  File "C:\PycharmProjects\circuitSim_tests\venv\lib\site-packages\ltspice\ltspice.py", line 81, in read_header
    if bytes([data[fp_line_end]]) == b'\n':
IndexError: index out of range

Process finished with exit code 1

**Comment by JTriggerFish** [comment]
main File below:

Version 4
SHEET 1 880 680
WIRE 528 -80 272 -80
WIRE 272 0 272 -80
WIRE 272 144 272 80
WIRE 272 176 272 144
WIRE 528 192 528 -80
WIRE 224 224 48 224
WIRE 240 272 192 272
WIRE 192 320 192 272
WIRE 288 320 288 288
WIRE 336 320 288 320
WIRE 256 448 256 288
WIRE 336 448 336 400
WIRE 336 448 256 448
WIRE 48 480 48 224
WIRE 192 480 192 400
WIRE 192 480 48 480
WIRE 336 480 336 448
WIRE 336 480 192 480
WIRE 528 480 528 272
WIRE 528 480 336 480
FLAG 528 480 0
FLAG 272 144 anode
SYMBOL res 256 -16 R0
WINDOW 0 34 30 Left 2
SYMATTR InstName R1
SYMATTR Value 100k
SYMBOL res 176 304 R0
SYMATTR InstName R2
SYMATTR Value 1k
SYMBOL Misc\\triodeh 272 224 R0
SYMATTR InstName U1
SYMBOL voltage 528 176 R0
WINDOW 3 24 152 Left 2
WINDOW 123 0 0 Left 0
WINDOW 39 24 124 Left 2
SYMATTR Value 250
SYMATTR SpiceLine Rser=1
SYMATTR InstName V2
SYMBOL voltage 336 304 R0
WINDOW 123 0 0 Left 0
WINDOW 39 24 124 Left 2
SYMATTR SpiceLine Rser=0.01
SYMATTR InstName V1
SYMATTR Value SINE(0 8.91 50)
TEXT -56 -104 Left 2 !.tran 15 startup uic
TEXT -56 -72 Left 2 !.inc dmtriodep.inc

**Comment by JTriggerFish** [comment]
My bad I was loading the wrong filetype: asc instead of raw - too long a day :) apologies
